/**
 * Provider Node's main process. Electron's main process is Node.js, not Bun — no Bun.serve,
 * bun:sqlite, etc. here, even though the rest of this monorepo prefers Bun; see the plan doc.
 */
import { app, BrowserWindow, ipcMain, shell } from "electron";
import { join } from "node:path";
import { existsSync } from "node:fs";
import { getRootEnvValue, loadRootEnvIntoProcess } from "./env-config";
import { registerAccountProvisioningIpc } from "./ipc/account-provisioning-ipc";
import { registerEnvConfigIpc } from "./ipc/env-config-ipc";
import { registerMirrorIpc } from "./ipc/mirror-ipc";
import { registerSettingsIpc } from "./ipc/settings-ipc";
import { restoredBounds, trackBounds } from "./window-state";

// Needed before anything below touches @decomp/privy-hedera (account-provisioning.ts's OPERATOR
// payer) — Electron's main process gets none of Bun's automatic .env loading.
loadRootEnvIntoProcess();

/**
 * A packaged build gets its icon from the .icns in the bundle (see package.json's build.mac.icon),
 * but a dev run has no bundle, so the Dock falls back to Electron's own logo. Point it at the same
 * artwork by hand — build/icon.png, generated by scripts/make-icon.cjs.
 */
function setDevDockIcon(): void {
  if (process.platform !== "darwin" || app.isPackaged) return;
  const icon = join(__dirname, "../../build/icon.png");
  if (existsSync(icon)) app.dock?.setIcon(icon);
}

function createWindow(): void {
  const win = new BrowserWindow({
    ...restoredBounds(),
    minWidth: 940,
    minHeight: 620,
    show: false,
    // The app draws its own toolbar (renderer/components/TitleBar.tsx) and insets it around the
    // traffic lights, so the window gets macOS chrome without a second, redundant title strip.
    titleBarStyle: "hiddenInset",
    trafficLightPosition: { x: 18, y: 18 },
    // Matches --ink, so the pre-paint frame isn't a white flash on a dark desktop.
    backgroundColor: "#070907",
    webPreferences: {
      // electron-vite names build output after the source file's own basename: src/main/preload.ts -> out/preload/preload.js.
      preload: join(__dirname, "../preload/preload.js"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false, // the preload script needs Node's ipcRenderer; the renderer content itself stays isolated
    },
  });
  win.once("ready-to-show", () => win.show());
  trackBounds(win);

  // Hashscan links and the like belong in the user's browser. Without this, target="_blank"
  // opens a second chromeless Electron window the user can't navigate or close cleanly.
  win.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:$/.test(new URL(url).protocol)) void shell.openExternal(url);
    return { action: "deny" };
  });

  if (process.env.ELECTRON_RENDERER_URL) {
    win.loadURL(process.env.ELECTRON_RENDERER_URL);
  } else {
    win.loadFile(join(__dirname, "../renderer/index.html"));
  }
}

ipcMain.handle("decomp:get-privy-app-id", () => getRootEnvValue("PRIVY_APP_ID"));
ipcMain.handle("decomp:open-external", (_event, url: string) => {
  if (/^https?:$/.test(new URL(url).protocol)) return shell.openExternal(url);
});
registerSettingsIpc();
registerMirrorIpc();
registerEnvConfigIpc();
registerAccountProvisioningIpc();

app.whenReady().then(() => {
  setDevDockIcon();
  createWindow();
  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});
